services:
  - type: web
    name: pw-classplus-bot
    env: python
    repo: https://github.com/chutpagludotnet/downCourse
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: AUTH_USERS
        sync: false
