services:
  - type: web
    name: SAINI TXT DIRECT 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: false
      - key: PORT
        value: 8000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: AUTH_USERS
        sync: false
